imports:
    - { resource: services.yml }

white_october_swift_mailer_db:
    entity_class: AppVentus\Awesome\SpoolMailerBundle\Entity\Mail

av_awesome_spool_mailer:
    contact_addresses:
      admin:
        address: admin@appventus.com
        name: "AppVentus"
      noreply:
        address: noreply@appventus.com
        name: "AppVentus"

swiftmailer:
    spool:
        type: db