services:
    instant_mailer:
        class: AppVentus\Awesome\SpoolMailerBundle\Mailer\InstantMailer
        arguments:
            - @doctrine.orm.entity_manager
            - @?swiftmailer.transport.real
            - %white_october.swiftmailer_db.spool.entity_class%

    spool_mailer:
        class: AppVentus\Awesome\SpoolMailerBundle\Mailer\SpoolMailer
        arguments:
            - @?swiftmailer.transport.real
            - @white_october.swiftmailer_db.spool

    fos_user.mailer.instant:
        class: "AppVentus\Awesome\SpoolMailerBundle\Mailer\FosInstantMailer"
        arguments:
            - "@instant_mailer"
            - "@router"
            - "@templating"
            - "@twig"
            - { confirmation.template: %fos_user.registration.confirmation.template%, resetting.template: %fos_user.resetting.email.template%, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% }}

    fos_user.mailer.default:
        alias: fos_user.mailer.instant

    spool.attachment_uploader:
        class: AppVentus\Awesome\SpoolMailerBundle\Utils\AttachmentUploader
        arguments:
            - '%spool_mailer.attachments_directory%'
            - '%kernel.root_dir%'

    spool.doctrine_attachment_listener:
        class: AppVentus\Awesome\SpoolMailerBundle\EventListener\AttachmentUploadListener
        arguments:
            - '@spool.attachment_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }