services:
    instant_mailer:
        class: AppVentus\Awesome\SpoolMailerBundle\Mailer\InstantMailer
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@?swiftmailer.transport.real"
            - "%white_october.swiftmailer_db.spool.entity_class%"

    spool_mailer:
        class: AppVentus\Awesome\SpoolMailerBundle\Mailer\SpoolMailer
        arguments:
            - "@?swiftmailer.transport.real"
            - "@white_october.swiftmailer_db.spool"

    spool.attachment_uploader:
        class: AppVentus\Awesome\SpoolMailerBundle\Utils\AttachmentUploader
        arguments:
            - '%spool_mailer.attachments_directory%'
            - '%kernel.root_dir%'

    spool.doctrine_attachment_listener:
        class: AppVentus\Awesome\SpoolMailerBundle\EventListener\AttachmentUploadListener
        arguments:
            - '@spool.attachment_uploader'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }